sudo: required
dist: trusty
language: generic

env:
  global:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - UPSTREAM_WORKSPACE=file
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
